name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies & Generate Lockfile
        run: |
          if [ -f "package.json" ]; then
            npm install --legacy-peer-deps
          elif [ -d "musica-app" ]; then
            cd musica-app
            npm install --legacy-peer-deps
          else
            echo "package.json não encontrado!"
            exit 1
          fi

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: Build on EAS
        run: |
          eas project:init --force --non-interactive || true
          eas build --platform android --profile preview --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
          EAS_NO_VCS: 1
